name: CI
on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: true

jobs:
  build:
    name: Typechecking & linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false
      - name: Install Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm run check

      - name: Check linting
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run check-fmt
